#Dockerfile for Development and Testing Environment
#This file should not be used for production
FROM node:12-stretch
RUN apt update && apt install bash
WORKDIR /root/app
# ENTRYPOINT ["/sbin/tini", "--"]
CMD npm run start
