export * as AccountController from './account.controller';
export * as AppointmentController from './appointment.controller';
export * as AuthController from './auth.controller';
export * as CosmobiologiaController from './cosmobiologia.controller';
export * as HealthController from './health.controller';
export * as HookController from './hook.controller';
export * as PermissionController from './permission.controller';
export * as RoleController from './role.controller';
export * as UserController from './user.controller';
