#Dockerfile for Development and Testing Environment
#This file should not be used for production
version: "3"
services:
  hectorgarcia-api:
    build:
      context: ../
      dockerfile: .docker/Dockerfile.local
    depends_on:
      - hectorgarcia-db
    ports:
      - "32800:3000"
    links:
      - hectorgarcia-db
    environment:
      - LOG_LEVEL=debug
      - DEBUG=true
      - PORT=3000
      - REQUEST_LIMIT=100kb
      - API_VERSION="1.0.0"
      - MONGO_HOST=hectorgarcia-db
      - MONGO_PORT=27017
      - MONGO_DB=tortugadescalza
      - MONGO_USER=user
      - MONGO_PASSWORD=password
      - USE_AUTH=false
    volumes:
      - ../:/root/app
      - ../../sweph:/root/sweph
  hectorgarcia-db:
    image: mongo:3.6
    ports:
      - "32817:27017"
    volumes:
      - hectorgarcia-mongodata:/data/db
volumes:
  hectorgarcia-mongodata:
networks:
  default:
    external:
      name: local-network
